nginx:
    build: ./nginx
    container_name: lamp-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - "php"
    volumes:
      - /var/www/logs/nginx:/var/log/nginx

php:
    build: ./php
    container_name: lamp-php
    ports:
      - "9000:9000"
    links:
      - "mysql"
      - "memcache"
      - "redis"
    volumes:
      - /var/www:/var/www

mysql:
    build: ./mysql
    container_name: lamp-mysql
    ports:
      - "3306:3306"
    volumes:
      - /var/www/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456

memcache:
    build: ./memcache
    container_name: lamp-memcache
    volumes_from:
          - data
    ports:
      - "11211:11211"

redis:
    build: ./redis
    container_name: lamp-redis
    volumes_from:
      - data
    ports:
      - "6379:6379"
